### PR TITLE
Install translation files in a separate binary libfm-qt5-data, to avoid conflicts with futur soname changes.

### PR DESCRIPTION
**Pull request by gilir**
I'm using a pull request to see if the changes are compliant with the package guidelines of the team.  I can push it to alioth if it's ok
The fix itself move the non .so files to a data binary. It will avoid conflict when the soname will change.

### CODE REVIEW

**Comment by agaida** [comment]
can you elaborate in which case this should help?

**Comment by gilir** [comment]
For example, when soname will change to 3, the package name will have to change to libfm-qt5-3. But, because of the translations files, you have to add a Conflicts / Breaks on libfm-qt5-2. That's reduce the interest of the debian library system.
FYI, it's a good practice to keep only .so in library binaries, to be able to install several versions of the library. That's make transition smoother.

**Comment by agaida** [comment]
I see the point - but to be true - i really don't want to have co-installable libraries in that case - in no way. There will be abi changes in the future somewhen - and i really want to break dependend packages. And indeed i like the idea of breaking the former version for that reason. A little bit more work, less mess.

Only two packages depending on libfm-qt, because libfm-qt is a high-level lib: pcmanfm-qt and lximage-qt. pcmanfm-qt and libfm-qt are built from the same source, so no problem, lximage (and maybe 2 or 3 Packages in the future) will use the version that comes with pcmanfm-qt. And again  - we don't want libfm-qt* to be co-installable. And the translations must match the version of the library in any way, that's the current state.

**Comment by gilir** [comment]
Sorry but you are just misusing debian mechanisms. Co-installation make transition smoother, the purpose is not keep them on the system forever. See https://www.netfort.gr.jp/~dancer/column/libpkg-guide/libpkg-guide.html if you want more information on dealing with shared library.

**Comment by agaida** [comment]
a) i don't think that i misunderstand nor misuse the mechanisms
b) the additional package has go through NEW - and we have to add breaks for the existing packages
c) yes - it will result in hold back packages or in proposed deinstallation of some things for a day or so - thats what sid is for as far as i understand it

So i'm still not convinced that this is a good idea

**Comment by agaida** [comment]
after some discussions in the team we came to the conclusion that we don't want to merge the PR

**Pull request closed without merging**
